spring.application.name=EvaluationMS

server.port=8086
loader.service.url=http://localhost:8085/loader
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.auto-create=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
kafka.topic.name=email-notification

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

destination.email="ruqaya@gmail.com"
