apiVersion: v1
kind: Service
metadata:
  labels:
    app: metric-app
  name: metric-service
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: metric-app
  type: NodePort
status:
  loadBalancer: {}
