apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor-app
  template:
    metadata:
      labels:
        app: processor-app
    spec:
      containers:
      - name: processor-app
        image: ranadaud89/processor-ms-app:latest
        ports:
        - containerPort: 8083
