apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: action-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-db
  template:
    metadata:
      labels:
        app: action-db
    spec:
      hostname: action-db
      containers:
      - name: action-db
        image: mysql:latest
        ports:
        - containerPort: 3307
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
