apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: roomdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roomdb
  template:
    metadata:
      labels:
        app: roomdb
    spec:
      hostname: roomdb
      containers:
      - name: roomdb
        image: mysql:latest
        ports:
        - containerPort: 3307
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
