apiVersion: v1
kind: ConfigMap
metadata:
  name: actiondb-config
data:
  MYSQL_HOST: "actionDB" 
  MYSQL_PORT: "3307"
  MYSQL_USER: "root"
  MYSQL_DATABASE: "actionDB"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"