apiVersion: v1
kind: Service
metadata:
  labels:
    app: sms-ns-app
  name: sms-ns-service
spec:
  ports:
  - port: 7071
    protocol: TCP
    targetPort: 7071
  selector:
    app: sms-ns-app
  type: NodePort
status:
  loadBalancer: {}
