spring.application.name=ProcessorMS

server.port=8084

metric.service.url=http://localhost:8083/metrics
loader.service.url=http://localhost:8085/loader

#metric.service.url=http://metric-app:8083/metrics
#loader.service.url=http://loader-app:8085/loader

action.queue.kafka.topic.name=jobs-queue
sms.kafka.topic.name=sms-notification
email.kafka.topic.name=email-notification

spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.bootstrap-servers=kafka-service:9092
spring.kafka.admin.auto-create=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer



