apiVersion: v1
kind: Service
metadata:
  labels:
    app: evaluation-app
  name: evaluation-service
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: evaluation-app
  type: NodePort
status:
  loadBalancer: {}
